package es.urjc.etsii.grafo.flayouts.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import es.urjc.etsii.grafo.io.Instance;

import java.util.*;

public class FLPInstance extends Instance {
    private static Comparator<FLPInstance> comparator = Comparator.comparing(FLPInstance::nFacilities).thenComparing(FLPInstance::getId);

    /**
     * Number of rows that van be generated by the solver
     */
    private final int nrows;

    /**
     * Lock facilities to a given row, 0 indexed
     */
    private final Map<Integer, Integer> preassignments;


    private final int[] lengths;
    private final int[][] weigths;

    @JsonCreator
    public FLPInstance(String name, int[] lengths, int[][] weigths, int nrows, Map<Integer, Integer> preassignments){
        super(name);
        this.lengths = lengths;
        this.weigths = weigths;
        this.nrows = nrows;
        this.preassignments = preassignments;
    }

    public static FLPInstance DRFLP(String name, int[] lengths, int[][] weigths){
        return new FLPInstance(name, lengths, weigths, 2, Collections.emptyMap());
    }

    /**
     * Number of rows that can be generated by the solver.
     * @return number of rows
     */
    public int nRows(){
        return this.nrows;
    }

    /**
     * Number of facilities
     * @return number of facilities
     */
    public int nFacilities(){
        return this.lengths.length;
    }

    /**
     * Length / width / size of a facility.
     * @param facility facility id, between 0 and n-1
     * @return size
     */
    public int length(int facility){
        return this.lengths[facility];
    }

    /**
     * Weight, flow, or cost between f1 and f2.
     * @param f1 facility1, between 0 and n-1
     * @param f2 facility2, between 0 and n-1
     * @return flow
     */
    public int flow(int f1, int f2){
        return this.weigths[f1][f2];
    }

    @Override
    public int compareTo(Instance o) {
        return comparator.compare(this, (FLPInstance) o);
    }

}
