package es.urjc.etsii.grafo.flayouts.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import es.urjc.etsii.grafo.io.Instance;

import java.util.*;

public class FLPInstance extends Instance {
    private static Comparator<FLPInstance> comparator = Comparator.comparing(FLPInstance::nFacilities).thenComparing(FLPInstance::getId);

    /**
     * Number of rows that van be generated by the solver
     */
    private final int nrows;

    /**
     * Maximum size of each row
     */
    private final int[] rowSizes;

    /**
     * Do all facilities have the same size?
     */
    private final boolean equalArea;

    /**
     * Is space allowed between facilities?
     */
    private final boolean allowSpace;

    /**
     * Lock facilities to a given row, 0 indexed
     */
    private final Map<Integer, Integer> preassignments;


    private final int[] lengths;
    private final int[][] weigths;

    @JsonCreator
    public FLPInstance(String name, int[] lengths, int[][] weigths, int nrows, int[] rowSizes, Map<Integer, Integer> preassignments, boolean equalArea, boolean allowSpace){
        super(name);
        this.lengths = lengths;
        this.weigths = weigths;
        this.nrows = nrows;
        this.rowSizes = rowSizes;
        this.preassignments = preassignments;
        this.equalArea = equalArea;
        this.allowSpace = allowSpace;
    }

    /**
     * Number of rows that can be generated by the solver.
     * @return number of rows
     */
    public int nRows(){
        return this.nrows;
    }

    /**
     * Number of facilities
     * @return number of facilities
     */
    public int nFacilities(){
        return this.lengths.length;
    }

    /**
     * Length / width / size of a facility.
     * @param facility facility id, between 0 and n-1
     * @return size
     */
    public int l(int facility){
        return this.lengths[facility];
    }

    /**
     * Weight, flow, or cost between f1 and f2.
     * @param f1 facility1, between 0 and n-1
     * @param f2 facility2, between 0 and n-1
     * @return flow
     */
    public int c(int f1, int f2){
        return this.weigths[f1][f2];
    }

    @Override
    public int compareTo(Instance o) {
        return comparator.compare(this, (FLPInstance) o);
    }

}
