package es.urjc.etsii.grafo.solver.services.events;

import es.urjc.etsii.grafo.solver.annotations.InheritedComponent;

/**
 * Implement this class to listen and react to the different events generated by the framework.
 *
 * @see <a href="https://mork-optimization.readthedocs.io/en/latest/features/events/">Docs event page</a>
 */
@InheritedComponent
public abstract class AbstractEventListener {

}
